services:
  searxng:
    image: searxng
    container_name: searxng

    ports:
      - "2000:8080"

    environment:
      BASE_URL: "https://localhost:2000/"

  nextcloud:
    image: nextcloud
    container_name: nextcloud

    depends_on: postgres

    ports:
      - "3000:80"
    
    expose:
      - 80

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud

  postgres:
    image: postgres:alpine
    container_name: postgres

    expose:
      - 5434

    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud

  wireguard:
    image: wireguard
    build: ./wireguard
    container_name: wireguard
    
    profiles:
      - port_forward

    cap_add:
      - NET_ADMIN

    volumes:
      - "./wireguard/tunnel.conf:/etc/wireguard/tunnel.conf"
