services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud

    depends_on: postgres

    ports:
      - "3000:80"
    
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud

  postgres:
    image: postgres:alpine
    container_name: postgres

    expose:
      - 5434

    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud

