version: "3.7"

services:
    vaultwarden:
        image: vaultwarden/server:alpine
        container_name: vaultwarden

        restart: always

        volumes:
          - "./data:/data"

        ports:
          - "3000:80"

        environment:
            SIGNUPS_ALLOWED: "false"
            INVITATIONS_ALLOWED: "false"
            SHOW_PASSWORD_HINT: "true"

