title: Dashboard
subtitle: Raspberry Pi

header: true
footer: false

theme: default

colors:
  light:
    highlight-primary: "#1a1a1a"
    highlight-secondary: "#1a1a1a"
    highlight-hover: "#252525"
    background: "#e2e2e2"
    card-background: "#1a1a1a"
    text: "#1a1a1a"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: "rgba(0, 0, 0, 0.4)"
    link: "#528cdd"
    link-hover: "#75acf9"
  dark:
    highlight-primary: "#1a1a1a"
    highlight-secondary: "#1a1a1a"
    highlight-hover: "#252525"
    background: "#0f0f0f"
    card-background: "#1a1a1a"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: "rgba(0, 0, 0, 0.4)"
    link: "#528cdd"
    link-hover: "#75acf9"

links:
  - name: Source
    icon: fab fa-github
    url: https://github.com/SystematicError/docker-homeserver
    target: _blank

services:
  - name: Applications
    icon: fas fa-cloud

    items:
      - name: Vaultwarden
        subtitle: Password Manager
        logo: assets/tools/vaultwarden.svg
        url: http://raspberry:3000
        target: _blank
      
      - name: Memos
        subtitle: Notes and Todo List
        url: http://raspberry:4000
        target: _blank

      - name: Tailscale
        subtitle: VPN Tunnel
        logo: assets/tools/tailscale.svg
        url: https://login.tailscale.com/welcome
        target: _blank

