version: "3.7"

services:
    memos:
        image: neosmemo/memos
        container_name: memos

        restart: unless-stopped

        volumes:
          - ./memos:/var/opt/memos

        ports:
          - 4000:5230

